name: Creating Json Input File

on:
  workflow_dispatch:

jobs:
  environment-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout central repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_GITHUB_PAT }}
          path: ./source-repo

      - name: Set up jq
        run: sudo apt-get install -y jq

      - name: Create output directory
        run: |
          if [ ! -d "${{ github.workspace }}/source-repo/output" ]; then
            mkdir -p "${{ github.workspace }}/source-repo/output"
          fi

      - name: Iterate Over Repos
        run: |
            #!/bin/bash

            # Define the input file and output JSON file
            INPUT_FILE="${{ github.workspace }}/source-repo/repositories.txt"
            OUTPUT_FILE="${{ github.workspace }}/source-repo/output/repositories.json"
        
            # Clear or create the output file
            > $OUTPUT_FILE
        
            # Initialize the JSON object
            echo "{" >> $OUTPUT_FILE
        
            # Read the repositories and classifications from the file
            while IFS=' ' read -r repo_name classification; do
                # Determine the organization based on the classification
                if [ "$classification" == "shared" ]; then
                    organisation="Legal-and-General-Shared"
                elif [ "$classification" == "confidential" ]; then
                    organisation="Legal-and-General-Confidential"
                else
                    organisation="Unknown-Classification"
                fi
        
                # Append the repository details to the JSON file
                echo "    \"$repo_name\": {" >> $OUTPUT_FILE
                echo "        \"repository\": \"$repo_name\"," >> $OUTPUT_FILE
                echo "        \"organisation\": \"$organisation\"" >> $OUTPUT_FILE
                echo "    }," >> $OUTPUT_FILE
            done < $INPUT_FILE
        
            # Remove the trailing comma from the last entry
            sed -i '$ s/,$//' $OUTPUT_FILE
        
            # Close the JSON object
            echo "}" >> $OUTPUT_FILE
        
            echo "JSON file created at ${OUTPUT_FILE}"
        
        

      - name: Upload environments and settings data
        uses: actions/upload-artifact@v4
        with:
            name: repositories.json
            path: ${{ github.workspace }}/source-repo/output

  
        
        
      