name: Creating Json Input File

on:
  workflow_dispatch:

jobs:
  creating-json:
    env:
        INPUT_FILE: "${{ github.workspace }}/source-repo/repositories.xlsx"
        OUTPUT_FILE: "${{ github.workspace }}/source-repo/output/repositories.json"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout central repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_GITHUB_PAT }}
          path: ./source-repo

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
         python-version: '3.10'
    
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install openpyxl

      - name: Set up jq
        run: sudo apt-get install -y jq

      - name: Create output directory
        run: |
          if [ ! -d "${{ github.workspace }}/source-repo/output" ]; then
            mkdir -p "${{ github.workspace }}/source-repo/output"
          fi

      - name: Iterate Over Repos
        run: python generate_json.py
        
        

      - name: Upload environments and settings data
        uses: actions/upload-artifact@v4
        with:
            name: repositories.json
            path: ${{ github.workspace }}/source-repo/output

  
        
        
      