name: Creating Json Input File

on:
  workflow_dispatch:

jobs:
  creating-json:
    env:
        INPUT_FILE: "${{ github.workspace }}/source-repo/repositories.xlsx"
        OUTPUT_FILE: "${{ github.workspace }}/source-repo/output/repositories.json"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout central repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_GITHUB_PAT }}
          path: ./source-repo

      - name: Set up jq
        run: sudo apt-get install -y jq

      - name: Create output directory
        run: |
          if [ ! -d "${{ github.workspace }}/source-repo/output" ]; then
            mkdir -p "${{ github.workspace }}/source-repo/output"
          fi

      - name: Iterate Over Repos
        run: |
            #!/bin/bash

            # Define the input Excel file and output JSON file
            INPUT_FILE="${{ github.workspace }}/source-repo/repositories.xlsx"
            OUTPUT_FILE="${{ github.workspace }}/source-repo/output/repositories.json"
        
            # Run the Python script to generate the JSON file
            python3 generate_json.py "$INPUT_FILE" "$OUTPUT_FILE"
        
        

      - name: Upload environments and settings data
        uses: actions/upload-artifact@v4
        with:
            name: repositories.json
            path: ${{ github.workspace }}/source-repo/output

  
        
        
      