name: Fetch Environment Variables

on:
  workflow_dispatch:

jobs:
  fetch-and-store:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GH_GITHUB_PAT }}
      GITHUB_WORKSPACE: ${{ github.workspace }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl

    - name: Fetch environment variables
      run: |
        chmod +x fetch_github_env_vars.sh
        ./fetch_github_env_vars.sh

    - name: Append data to Excel
      run: |
        python append_to_excel.py

    - name: Upload output
      uses: actions/upload-artifact@v2
      with:
        name: environment-variables
        path: env_vars.xlsx
