name: Replace Strings ALL

on:
  workflow_dispatch:
    # inputs:
    #     repository:
    #       type: string
    #       description: 'Repository name'
    #       required: true
    #     organisation:
    #       description: 'organisation name'
    #       type: string
    #       required: true_or_false

jobs:
  replace-strings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_GITHUB_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.0-alpha.6

      - name: Install dependencies
        run: |  
          python -m pip install --upgrade pip
          pip install openpyxl

      - name: Replace Strings in YML files
        run: |
          python string-replaces-all.py
        env:
          EXCEL_FILE: "team_mapping.xlsx"
          GITHUB_WORKSPACE: ${{ github.workspace }}
        shell: bash
