name: Replace Organization Strings

on:
  workflow_dispatch:

jobs:
  replace_organization:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openpyxl

    - name: Run replacement script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python replace_organization.py

    - name: Commit and push changes
      if: github.ref == 'refs/heads/main'
      run: |
        git config --global user.name 'KrushnaPimpale'
        git config --global user.email 'kpimple656@gmail.com'
        git add .
        git commit -m 'Replace organization strings'
        git push
